'use client'

/**
 * ExplanationMarkdown — Gemini-generated narrative with numeric-slot
 * highlighting + 3-section scaffolding per Step 4 §3.1.
 *
 * We intentionally do NOT pull in a full markdown renderer. The Copilot
 * always emits a short narrative (max ~4 paragraphs) structured as:
 *
 *     What AI sees: ...
 *     Why now: ...
 *     What invalidates: ...
 *
 * We split on those headings and render three collapsible sections.
 * Inline numbers (percentages, prices, ratios) get colored per the
 * ``model-*`` identity map so the reader's eye latches onto them.
 */

import { useState } from 'react'
import { ChevronDown } from 'lucide-react'

interface Props {
  /** Raw Gemini reply text. Empty = render placeholder. */
  text: string
  /** Optional: when present, "Generated by Gemini · 2.1s" meta footer. */
  duration_ms?: number
}

const SECTION_TITLES = [
  'What AI sees',
  'Why now',
  'What invalidates',
] as const

type SectionTitle = typeof SECTION_TITLES[number]

export default function ExplanationMarkdown({ text, duration_ms }: Props) {
  const sections = splitSections(text)
  const [open, setOpen] = useState<Record<SectionTitle, boolean>>(
    { 'What AI sees': true, 'Why now': true, 'What invalidates': false },
  )

  if (!text || text.trim().length === 0) {
    return (
      <div className="trading-surface text-[12px] text-d-text-muted italic">
        No AI explanation generated yet.
      </div>
    )
  }

  return (
    <div className="trading-surface !p-0 overflow-hidden">
      {SECTION_TITLES.map((title, idx) => {
        const body = sections[title] || (idx === 0 ? text : '')
        if (!body.trim()) return null
        const isOpen = open[title]
        return (
          <div key={title} className={idx > 0 ? 'border-t border-d-border' : ''}>
            <button
              onClick={() => setOpen({ ...open, [title]: !isOpen })}
              className="w-full flex items-center justify-between px-5 py-3 hover:bg-white/[0.02] transition-colors"
            >
              <span className="text-[12px] font-medium text-white">{title}</span>
              <ChevronDown
                className={`w-3.5 h-3.5 text-d-text-muted transition-transform ${isOpen ? '' : '-rotate-90'}`}
              />
            </button>
            {isOpen && (
              <div className="px-5 pb-4 text-[13px] text-d-text-primary leading-relaxed">
                {highlightNumbers(body)}
              </div>
            )}
          </div>
        )
      })}

      {duration_ms !== undefined && (
        <div className="px-5 py-2 border-t border-d-border text-[10px] text-d-text-muted">
          Generated by Gemini ·{' '}
          <span className="numeric">{(duration_ms / 1000).toFixed(1)}s</span>
        </div>
      )}
    </div>
  )
}

// --------------------------------------------------------------- sections

function splitSections(text: string): Partial<Record<SectionTitle, string>> {
  const out: Partial<Record<SectionTitle, string>> = {}
  // Accept variations: "**What AI sees:**", "### What AI sees", "What AI sees —"
  const pattern = new RegExp(
    `(?:\\*\\*|###\\s+|^|\\n)\\s*(${SECTION_TITLES.join('|')})\\s*(?::|—|-)\\s*`,
    'gi',
  )
  const matches = Array.from(text.matchAll(pattern))
  if (matches.length === 0) return {}
  for (let i = 0; i < matches.length; i++) {
    const cur = matches[i]
    const next = matches[i + 1]
    const title = cur[1] as SectionTitle
    const start = (cur.index || 0) + cur[0].length
    const end = next ? next.index : text.length
    out[title] = text.slice(start, end).replace(/\*\*/g, '').trim()
  }
  return out
}

// -------------------------------------------------------- number highlight

/**
 * Wrap runs that look like a number / ratio / percent in a colored span.
 * We keep the color choice simple: teal for everything — resisting the
 * temptation to parse which model each number belongs to. Step 4 spec
 * allows a future refinement (parse ``TFT +2.1%`` → color as model-tft).
 */
function highlightNumbers(text: string): (string | React.ReactNode)[] {
  const tokens = text.split(/(\b[+−-]?\d[\d,]*(?:\.\d+)?%?(?:\s*(?:pp|bps|x|\u20B9))?\b|\u20B9\d[\d,]*(?:\.\d+)?)/g)
  return tokens.map((tok, i) => {
    if (!tok) return null
    if (
      /^\b[+\-−]?\d[\d,]*(?:\.\d+)?%?(?:\s*(?:pp|bps|x|\u20B9))?\b$/.test(tok)
      || /^\u20B9\d[\d,]*(?:\.\d+)?$/.test(tok)
    ) {
      return (
        <span
          key={i}
          className="numeric font-medium text-primary"
        >
          {tok}
        </span>
      )
    }
    return <span key={i}>{tok}</span>
  })
}
